window.HSE_DATA = {
  version: "1.0.0",
  storageKey: "her-strongest-era-kickstart-v1",
  brand: {
    name: "Her Strongest Era",
    shortName: "Strongest Era",
    owner: "Emma | EPC Athletics",
    themeColor: "#dc4f7b",
    backgroundColor: "#fff7f9",
    contactUrl: "https://kxros.io/epcathletics/",
  },
  offers: {
    starterSystem: {
      label: "Strongest Era Starter System",
      url: "../oto/",
      headline: "Turn this momentum into your four-week system.",
    },
    coaching: {
      label: "Apply for 1:1 Coaching",
      url: "https://kxros.io/epcathletics/#download",
      headline: "Get personalized support for your next chapter.",
    },
  },
  onboardingOptions: [
    "I feel off track",
    "I want to rebuild consistency",
    "I want to feel stronger",
    "I want more energy",
    "I want to improve my eating habits",
    "I am going through a personal reset",
    "I am tired of starting over",
  ],
  assessmentMetrics: [
    "Energy",
    "Sleep",
    "Hydration",
    "Nutrition awareness",
    "Daily movement",
    "Strength and fitness",
    "Stress management",
    "Confidence",
    "Consistency",
    "Trust in yourself",
  ],
  habits: [
    "Water goal",
    "Nutrition logged",
    "Protein included",
    "Step goal",
    "Workout or intentional movement",
    "Journal completed",
    "Daily reframe read",
    "Sleep target",
    "One promise kept",
  ],
  days: [
    {
      day: 1,
      theme: "Tell the Truth",
      purpose: "Awareness before change.",
      focus: "Create an honest baseline without trying to fix everything at once.",
      physical: "Take a 20-minute walk or complete the beginner full-body session.",
      nutrition: "Log what you eat without judgment and record your water intake.",
      reframe: "You cannot shame yourself into becoming someone you love.",
      journal: "What have I been avoiding admitting about the way I currently feel?",
      proof: "Complete the day without trying to fix everything.",
      lesson: "Nutrition Awareness",
    },
    {
      day: 2,
      theme: "Build the Baseline",
      purpose: "Create structure.",
      focus: "Make the next right actions easier to repeat.",
      physical: "Choose tomorrow's movement time and protect it.",
      nutrition: "Set a realistic water target and plan tomorrow's protein sources.",
      reframe: "Consistency becomes easier when the environment stops fighting you.",
      journal: "Which parts of my environment support the woman I want to become, and which parts reinforce the version I am trying to leave behind?",
      proof: "Remove one friction point before tomorrow.",
      lesson: "Hydration",
    },
    {
      day: 3,
      theme: "Fuel Yourself",
      purpose: "Food as support rather than punishment.",
      focus: "Build one balanced plate and observe how it feels.",
      physical: "Add a short walk after one meal.",
      nutrition: "Include protein in your primary meals and eat one fruit or vegetable.",
      reframe: "Food is not a test of whether I am good or bad. It is a tool I can learn to use.",
      journal: "What food rules have I inherited that may no longer serve me?",
      proof: "Build one stronger plate today.",
      lesson: "Stronger Plate",
    },
    {
      day: 4,
      theme: "Prove You Can Move",
      purpose: "Build physical evidence.",
      focus: "Use movement to collect proof, not punishment.",
      physical: "Complete the Full-Body Momentum workout or a reduced version.",
      nutrition: "Hydrate before and after training.",
      reframe: "I do not move because I hate my body. I move because I am building a stronger relationship with it.",
      journal: "How does movement change the way I think, feel, and carry myself?",
      proof: "Record your energy before and after movement.",
      lesson: "Movement and Steps",
    },
    {
      day: 5,
      theme: "Interrupt the Pattern",
      purpose: "Respond differently.",
      focus: "Notice the cue before the automatic behavior.",
      physical: "Take a 10-minute pattern-interrupt walk.",
      nutrition: "Complete the Craving Check before one automatic choice.",
      reframe: "An urge is not an instruction.",
      journal: "What usually happens immediately before I abandon my goals?",
      proof: "Choose one conscious response today.",
      lesson: "Cravings Without Chaos",
    },
    {
      day: 6,
      theme: "Become Visible",
      purpose: "Stop hiding from progress.",
      focus: "Let evidence replace waiting.",
      physical: "Complete intentional movement and wear something that creates confidence.",
      nutrition: "Repeat your strongest nutrition habit from earlier this week.",
      reframe: "Visibility is not vanity. Sometimes it is accountability, courage, and evidence that I am no longer hiding.",
      journal: "Where in my life have I been waiting to become more confident before allowing myself to be seen?",
      proof: "Take a photo, video, or written progress update.",
      lesson: "Reframes",
    },
    {
      day: 7,
      theme: "Keep the Promise",
      purpose: "Reflect and continue.",
      focus: "Turn this week into the next seven days.",
      physical: "Repeat the movement that made you feel strongest this week.",
      nutrition: "Review food, water, movement, mood, and energy patterns.",
      reframe: "The end of this week is not the finish line. It is proof that I can begin.",
      journal: "What did this week teach me about the woman I am capable of becoming?",
      proof: "Build your next seven-day commitment.",
      lesson: "Next Seven Days",
    },
  ],
  lessons: [
    {
      id: "hydration",
      title: "Hydration",
      points: ["Water supports energy, workouts, digestion, focus, and hunger awareness.", "The best target is the one you can see, repeat, and adjust.", "Start by making water easier before making the goal bigger."],
      takeaway: "Hydration is a visibility habit first.",
      action: "Choose one water anchor: after waking, with meals, or around training.",
      tool: "hydration",
    },
    {
      id: "nutrition",
      title: "Nutrition Awareness",
      points: ["Calories are energy, not morality.", "Observation comes before restriction.", "One meal does not define progress."],
      takeaway: "Honest tracking creates information, not judgment.",
      action: "Log one meal today exactly as it happened.",
      tool: "plate",
    },
    {
      id: "tracking",
      title: "Food Tracking",
      points: ["Use the same entries consistently.", "Watch oils, sauces, and cooked versus uncooked amounts.", "Review patterns instead of attacking yourself."],
      takeaway: "Tracking is a mirror, not a punishment.",
      action: "Track one full day without changing the day to look better.",
      tool: "momentum",
    },
    {
      id: "plate",
      title: "Stronger Plate",
      points: ["Build around protein, produce, carbs, and fat or flavor.", "Satisfaction matters.", "Convenience is allowed."],
      takeaway: "A strong plate should support real life.",
      action: "Build one simple plate with the plate builder.",
      tool: "plate",
    },
    {
      id: "protein",
      title: "Protein Made Simple",
      points: ["Protein supports recovery, strength, and satiety.", "A useful first goal is protein in primary meals.", "You do not need perfection to improve meal quality."],
      takeaway: "Protein is a repeatable anchor.",
      action: "Choose tomorrow's easiest protein source.",
      tool: "plate",
    },
    {
      id: "cravings",
      title: "Cravings Without Chaos",
      points: ["Cravings may reflect hunger, low protein, stress, sleep, restriction, or environment.", "A craving is information, not an emergency.", "The goal is a conscious response."],
      takeaway: "Pause long enough to understand the signal.",
      action: "Run the Craving Check once today.",
      tool: "craving",
    },
    {
      id: "movement",
      title: "Movement and Steps",
      points: ["Movement beyond workouts counts.", "Short blocks protect momentum.", "Realistic increases beat dramatic spikes."],
      takeaway: "The minimum keeps the identity alive.",
      action: "Take one short walk after a meal.",
      tool: "minimum",
    },
  ],
  workouts: [
    {
      id: "full-body",
      title: "Full-Body Momentum",
      level: "Structured",
      details: ["3 rounds", "Squat variation x 10", "Incline push-up or chest press x 8", "Hip hinge or Romanian deadlift x 10", "Row variation x 10", "Glute bridge x 12", "Plank or dead bug x 30 seconds"],
      cue: "Rest 60-90 seconds. Choose control over speed.",
    },
    {
      id: "lower-glutes",
      title: "Lower Body and Glutes",
      level: "Strength",
      details: ["Goblet squat x 10", "Hip thrust x 12", "Reverse lunge x 8 each side", "Romanian deadlift x 10", "Banded abduction x 15", "Calf raise x 12"],
      cue: "Move through a range you can control.",
    },
    {
      id: "low-energy",
      title: "Low-Energy Reset",
      level: "Minimum viable",
      details: ["5-minute mobility", "10-minute walk", "2 strength movements", "Gentle stretch", "1 minute of breathing"],
      cue: "A reduced habit protects momentum better than abandoning the habit.",
    },
  ],
  recipes: [
    { title: "High-Protein Breakfast Bowl", protein: "Greek yogurt, berries, granola, chia, honey", prep: "Layer everything in a bowl. Add protein powder if desired.", note: "Vegetarian friendly." },
    { title: "Egg and Vegetable Wrap", protein: "Eggs, egg whites, wrap, spinach, peppers, cheese", prep: "Scramble, fill, fold, and toast.", note: "Swap eggs for tofu scramble if preferred." },
    { title: "Chicken Rice Power Bowl", protein: "Chicken, microwave rice, frozen vegetables, sauce", prep: "Heat, combine, and season.", note: "Emergency meal approved." },
    { title: "High-Protein Pasta", protein: "Lean meat or lentil pasta, marinara, vegetables", prep: "Cook pasta, add protein and sauce, finish with vegetables.", note: "Use chickpea pasta for a vegetarian option." },
    { title: "Taco Bowl", protein: "Ground turkey, beans, rice, salsa, lettuce, avocado", prep: "Cook protein, assemble bowl, add flavor.", note: "Easy to meal prep." },
    { title: "Greek Yogurt Dessert Bowl", protein: "Greek yogurt, fruit, chocolate chips, nut butter", prep: "Mix and chill for ten minutes.", note: "Satisfying sweet option." },
    { title: "Protein Smoothie", protein: "Protein powder, milk, banana, berries, spinach", prep: "Blend until smooth.", note: "Add oats for more carbs." },
  ],
  shopping: ["Eggs", "Greek yogurt", "Chicken", "Microwave rice", "Frozen vegetables", "Fruit", "Wraps", "Protein powder", "Seasonings", "One enjoyable snack"],
  reframes: [
    "Motivation was never meant to carry the entire journey.",
    "A bad meal does not require a bad day.",
    "Starting small is not the same as thinking small.",
    "You do not have to feel confident before acting confidently.",
    "Discipline is not punishment. It is self-respect made visible.",
    "Missing once is an event. Missing repeatedly becomes a pattern.",
    "The plan can bend without breaking.",
    "Progress that feels sustainable is not too slow.",
    "Your body is not a problem to solve before your life can begin.",
    "You do not need a new identity. You need evidence of the one already trying to emerge.",
    "The woman you want to become is built through ordinary decisions.",
  ],
  recommendationRules: [
    {
      id: "overwhelmed-restarter",
      label: "The Overwhelmed Restarter",
      checks: { consistencyMax: 4, trustMax: 5, stressMin: 7 },
      focus: "Protect momentum with minimum viable actions.",
      secondary: "Reduce friction before adding intensity.",
      habits: ["Water goal", "One promise kept", "Journal completed"],
      workout: "Low-Energy Reset",
      lesson: "Movement and Steps",
      nextStep: "28-day-challenge",
    },
    {
      id: "all-or-nothing-achiever",
      label: "The All-or-Nothing Achiever",
      checks: { consistencyMax: 5, nutritionMin: 6 },
      focus: "Prioritize flexibility over perfection.",
      secondary: "Track promise-keeping instead of perfect execution.",
      habits: ["One promise kept", "Daily reframe read", "Nutrition logged"],
      workout: "Full-Body Momentum",
      lesson: "Cravings Without Chaos",
      nextStep: "starter-system",
    },
    {
      id: "under-fueled-striver",
      label: "The Under-Fueled Striver",
      checks: { energyMax: 5, proteinOften: false },
      focus: "Use regular balanced meals to support energy.",
      secondary: "Avoid aggressive restriction this week.",
      habits: ["Protein included", "Water goal", "Sleep target"],
      workout: "Low-Energy Reset",
      lesson: "Protein Made Simple",
      nextStep: "starter-system",
    },
    {
      id: "disconnected-caregiver",
      label: "The Disconnected Caregiver",
      checks: { movementMax: 5, confidenceMax: 5 },
      focus: "Create small protected rituals.",
      secondary: "Schedule ten-minute movement blocks.",
      habits: ["Workout or intentional movement", "Journal completed", "One promise kept"],
      workout: "Low-Energy Reset",
      lesson: "Movement and Steps",
      nextStep: "coaching",
    },
    {
      id: "ready-rebuilder",
      label: "The Ready Rebuilder",
      checks: {},
      focus: "Complete the full seven-day scorecard.",
      secondary: "Use structure to turn willingness into proof.",
      habits: ["Step goal", "Workout or intentional movement", "Nutrition logged"],
      workout: "Full-Body Momentum",
      lesson: "Nutrition Awareness",
      nextStep: "starter-system",
    },
  ],
};
