const acts=[
{id:'I',title:'Reset the Frame',start:1},{id:'II',title:'Strategy Before Systems',start:5},{id:'III',title:'The Modern Content Machine',start:9},{id:'IV',title:'The Five Walls',start:14},{id:'V',title:'Diagnose the Current Machine',start:18},{id:'VI',title:'Define the Gap',start:23},{id:'VII',title:'How AI Closes the Gap',start:26},{id:'VIII',title:'Design Their Content OS',start:30}
];
const slides=[
{act:'I',mode:'FRAME',className:'title-slide',html:`<div class="slide-tag">LIVE DIAGNOSTIC TRAINING</div><h1 class="display">CONTENT <span>OS</span></h1><p class="lede">Better content. More consistently.<br><strong>Less founder friction.</strong></p><div class="title-rail"><span>CREATE</span><span>DISTRIBUTE</span><span>LEARN</span></div>`,objective:'Open with the desired transformation, not the implementation details.',ask:'What would make this session materially useful for you?',listen:'A concrete quality, consistency, time, or growth outcome.',capture:'The founder’s primary success condition.'},
{act:'I',mode:'TEACH',className:'act-divider',html:`<div class="slide-tag">ACT I / RESET THE FRAME</div><div class="act-number">I</div><h2>How should we actually think about AI + content?</h2><p>AI is not the creator. It is leverage around the creator.</p>`,objective:'Reset weak mental models before discussing tools.',ask:'When you think about AI and content today, what role do you imagine it playing?',listen:'Magic-button expectations or fear of losing authenticity.',capture:'Current AI assumptions.'},
{act:'I',mode:'TEACH',html:`<div class="slide-tag">AI IS AN EMPLOYEE, NOT A MAGIC BUTTON</div><div class="employee"><div class="employee-core">AI<br>EMPLOYEE</div><div class="employee-inputs"><div><b>01 / CONTEXT</b><span>What it knows</span></div><div class="step"><b>02 / ROLE</b><span>Who it is</span></div><div class="step"><b>03 / TASK</b><span>What good looks like</span></div><div class="step"><b>04 / PROCESS</b><span>How work gets done</span></div><div class="step"><b>05 / REVIEW</b><span>How it improves</span></div></div></div>`,objective:'Make AI performance feel understandable and operational.',ask:'Which of these inputs is weakest in your current AI use?',listen:'Missing context, vague role, unclear quality bar, or no review loop.',capture:'The first AI management gap.'},
{act:'I',mode:'TEACH',html:`<div class="slide-tag">AI-POWERED. HUMAN-POLISHED.</div><div class="split"><article class="split-card"><small>AI EXPANDS</small><h3>Human<br>creativity.</h3><p>Search. Synthesize. Organize. Explore. Execute.</p></article><article class="split-card signal step"><small>HUMAN PRESERVES</small><h3>Taste.<br>Judgment.</h3><p>Stories. Experience. Conviction. Final voice.</p></article></div><p class="footer-claim">Automate the labor. <span class="accent">Preserve the judgment.</span></p>`,objective:'Establish the human–AI division of labor.',ask:'Where does your judgment create disproportionate value?',listen:'Taste, lived experience, opinion, consequence, or trust.',capture:'Protected human decisions.'},
{act:'I',mode:'MAP',html:`<div class="slide-tag">IDEA GOLD IS ALREADY EVERYWHERE</div><h2 class="display medium">You do not need more ideas.<br><span class="accent">You need extraction infrastructure.</span></h2><div class="source-field"><span>CONVERSATIONS</span><span>CLIENT CALLS</span><span>PODCASTS</span><span>VOICE NOTES</span><span>EXPERIENCE</span><span>STORIES</span><span>RESEARCH</span><span>OPINIONS</span><span>QUESTIONS</span><span>DISAGREEMENTS</span><span>LESSONS</span><span class="hot">UNTAPPED SIGNAL</span></div>`,objective:'Reframe idea scarcity as an extraction problem.',ask:'Where does your best thinking naturally show up?',listen:'High-frequency sources rich in original detail.',capture:'Priority signal sources.'},
{act:'II',mode:'TEACH',className:'act-divider',html:`<div class="slide-tag">ACT II / STRATEGY BEFORE SYSTEMS</div><div class="act-number">II</div><h2>What are we actually trying to make the machine do?</h2><p>Strategy determines the machine.</p>`,objective:'Choose the destination before designing the operating system.',ask:'What should content ultimately produce for the business?',listen:'A concrete business outcome rather than a publishing target.',capture:'Primary strategic outcome.'},
{act:'II',mode:'MAP',html:`<div class="slide-tag">THE FOUR STRATEGIC INPUTS</div><h2 class="display small">The machine follows<br><span class="accent">the strategy.</span></h2><div class="four-inputs"><article class="big-card"><b>01</b><h3>BUSINESS<br>GOAL</h3><p>What must content produce?</p></article><article class="big-card step"><b>02</b><h3>AUDIENCE</h3><p>Who specifically needs to care?</p></article><article class="big-card step"><b>03</b><h3>OFFER</h3><p>Where should attention move?</p></article><article class="big-card signal step"><b>04</b><h3>POSITION</h3><p>Why should they listen to you?</p></article></div>`,objective:'Collect only the strategic inputs that change system architecture.',ask:'Which of these four is least clear today?',listen:'Generic audience, weak destination, or interchangeable positioning.',capture:'Goal, audience, offer, and position.'},
{act:'II',mode:'ASK',html:`<div class="slide-tag">POSITIONING + COUNTER-POSITIONING</div><h2 class="display small">What territory can<br><span class="accent">you credibly own?</span></h2><div class="position-questions"><p>What does your category get wrong?</p><p class="step">What will you say that competitors won’t?</p><p class="step">What should your name become synonymous with?</p></div>`,objective:'Turn AI into a strategic thinking partner around a distinct position.',ask:'What do you believe that your category gets wrong?',listen:'Specific conviction rooted in experience and evidence.',capture:'Counter-position and ownable territory.'},
{act:'II',mode:'TEACH',html:`<div class="slide-tag">THE STRATEGIC SHIFT</div><h2 class="display">Not a publishing machine.</h2><p class="lede step"><strong>An idea-distribution machine</strong><br>built around a strategic position.</p><div class="flow compact"><span>POSITION</span><i>→</i><span>IDEAS</span><i>→</i><span>ASSETS</span><i>→</i><span>AUDIENCE</span><i>→</i><span>OUTCOME</span></div>`,objective:'Tie publishing operations to strategic position and business outcomes.',ask:'Does your current content consistently reinforce one recognizable position?',listen:'Scattered topics or content disconnected from the offer.',capture:'Strategic through-line.'},
{act:'III',mode:'TEACH',className:'act-divider',html:`<div class="slide-tag">ACT III / THE MODERN CONTENT MACHINE</div><div class="act-number">III</div><h2>What could a properly designed system actually do?</h2><p>Three engines. One learning machine.</p>`,objective:'Zoom out and show the client-facing model of the Content OS.',ask:'Which engine would create the most leverage for you today?',listen:'A clear creation, distribution, or learning constraint.',capture:'Priority engine.'},
{act:'III',mode:'MAP',html:`<div class="slide-tag">THE THREE ENGINES</div><h2 class="display small">Create. Distribute.<br><span class="accent">Learn.</span></h2><div class="three-engines"><article class="big-card signal"><b>01</b><h3>CREATION<br>ENGINE</h3><p>Knowledge becomes valuable ideas and assets.</p></article><article class="big-card step"><b>02</b><h3>DISTRIBUTION<br>ENGINE</h3><p>Valuable work travels further.</p></article><article class="big-card step"><b>03</b><h3>INTELLIGENCE<br>ENGINE</h3><p>Every cycle makes the next one smarter.</p></article></div>`,objective:'Give the whole system a simple three-function model.',ask:'Where is your machine strongest and weakest?',listen:'Asymmetry—for example, strong creation with weak distribution.',capture:'Current engine maturity.'},
{act:'III',mode:'TEACH',html:`<div class="slide-tag">01 / CREATION ENGINE</div><h2 class="display medium">Turn knowledge into<br><span class="accent">valuable assets.</span></h2><div class="flow"><span>RAW<br>KNOWLEDGE</span><i>→</i><span>IDEAS</span><i>→</i><span>ANGLES</span><i>→</i><span>ASSETS</span></div><p class="footer-claim">Extract. Research. Connect. Develop. Create.</p>`,objective:'Show the transformation from buried knowledge to usable content.',ask:'Where does your creation chain currently slow down?',listen:'Extraction, research, angle selection, or execution bottlenecks.',capture:'Weakest creation stage.'},
{act:'III',mode:'TEACH',html:`<div class="slide-tag">02 / DISTRIBUTION ENGINE</div><h2 class="display medium">Increase<br><span class="accent">surface area.</span></h2><div class="surface-map"><div class="surface-source">ONE<br>VALUABLE<br>IDEA</div><div class="surface-assets"><span>LONG VIDEO</span><span>7 SHORTS</span><span>CAROUSEL</span><span>EMAIL</span><span>THREADS</span><span>STORIES</span></div></div><p class="footer-claim">More reach. Not proportionally more founder effort.</p>`,objective:'Make distribution leverage tangible.',ask:'How many meaningful assets does one strong idea become today?',listen:'One-and-done publishing or underused long-form source material.',capture:'Current and desired content multiplication ratio.'},
{act:'III',mode:'TEACH',html:`<div class="slide-tag">03 / INTELLIGENCE ENGINE</div><h2 class="display medium">Learn what works.<br><span class="accent">Create better.</span></h2><div class="cycle"><span>CREATE</span><i>→</i><span>DISTRIBUTE</span><i>→</i><span>LEARN</span><i>→</i><span>CREATE<br>BETTER</span></div><p class="footer-claim">A real content machine is a learning system.</p>`,objective:'Establish learning as a core engine rather than an analytics afterthought.',ask:'How does prior performance change what you create next?',listen:'Manual review, intuition only, or learning that never re-enters the workflow.',capture:'Existing feedback signals and review process.'},
{act:'IV',mode:'TEACH',className:'act-divider',html:`<div class="slide-tag">ACT IV / THE FIVE WALLS</div><div class="act-number">IV</div><h2>If this is possible, why doesn’t everyone work this way?</h2><p>Because every creator eventually hits the same walls.</p>`,objective:'Introduce constraints after the audience understands the possibility.',ask:'Which wall feels most familiar?',listen:'The constraint with the strongest emotional recognition.',capture:'Likely primary wall.'},
{act:'IV',mode:'MAP',html:`<div class="slide-tag">THE FIVE WALLS</div><h2 class="display small">Your ceiling is often<br><span class="accent">infrastructure.</span></h2><div class="five-walls"><article class="big-card"><b>01</b><h3>CONTEXT</h3><p>AI doesn’t know me.</p></article><article class="big-card step"><b>02</b><h3>IDEA</h3><p>I don’t know what to say.</p></article><article class="big-card step"><b>03</b><h3>CREATION</h3><p>Good work takes too long.</p></article><article class="big-card step"><b>04</b><h3>DISTRIBUTION</h3><p>Everything dies after one use.</p></article><article class="big-card signal step"><b>05</b><h3>FEEDBACK</h3><p>The system never learns.</p></article></div>`,objective:'Map the five constraints directly onto the content machine.',ask:'Which wall is currently setting the ceiling?',listen:'One repeated point of failure affecting quality, volume, time, or leverage.',capture:'Wall ranking.'},
{act:'IV',mode:'TEACH',html:`<div class="slide-tag">WALLS 01–03 / BEFORE PUBLISHING</div><div class="wall-row"><b>CONTEXT</b><p><strong>Fragmented knowledge</strong><span>The system cannot think with you.</span></p></div><div class="wall-row step"><b>IDEA</b><p><strong>Weak optionality</strong><span>Knowledge does not become enough strong angles.</span></p></div><div class="wall-row step"><b>CREATION</b><p><strong>Founder-heavy execution</strong><span>Quality content costs too much time.</span></p></div>`,objective:'Clarify the upstream walls that stop work before publishing.',ask:'Where does valuable knowledge stop moving?',listen:'Scattered context, inconsistent ideation, or labor-heavy production.',capture:'Upstream constraint.'},
{act:'IV',mode:'TEACH',html:`<div class="slide-tag">WALLS 04–05 / AFTER PUBLISHING</div><div class="wall-row"><b>DISTRIBUTION</b><p><strong>One-and-done assets</strong><span>Valuable work reaches a fraction of its audience.</span></p></div><div class="wall-row step"><b>FEEDBACK</b><p><strong>No compounding intelligence</strong><span>Performance never improves the next cycle.</span></p></div><h2 class="display small step" style="margin-top:56px">Creativity is not always the ceiling.<br><span class="accent">Infrastructure is.</span></h2>`,objective:'Show how value leaks after publishing.',ask:'What percentage of a strong idea’s potential do you think you capture?',listen:'Low reuse and disconnected analytics.',capture:'Downstream leverage loss.'},
{act:'V',mode:'ASK',className:'act-divider',html:`<div class="slide-tag">ACT V / DIAGNOSE THE CURRENT MACHINE</div><div class="act-number">V</div><h2>Where is your system actually breaking today?</h2><p>Audit the engines. Find the friction.</p>`,objective:'Shift from teaching into a personal diagnostic.',ask:'Where are you losing the most quality, volume, time, or leverage?',listen:'Repeated operational pain with meaningful impact.',capture:'Initial diagnostic hypothesis.'},
{act:'V',mode:'ASK',html:`<div class="slide-tag">DIAGNOSTIC / CREATION</div><h2 class="display small">Can you reliably turn knowledge into <span class="accent">great content?</span></h2><div class="question-stack"><p>Where do your strongest ideas come from?</p><p class="step">What takes the most time?</p><p class="step">What do you avoid because it is too labor-intensive?</p><p class="step">Where does quality fall below your standard?</p></div>`,objective:'Diagnose the creation engine without wandering into random questions.',ask:'Where does the creation engine lose momentum or quality?',listen:'Inconsistent ideas, labor-heavy stages, and avoided formats.',capture:'Creation bottleneck and consequences.'},
{act:'V',mode:'ASK',html:`<div class="slide-tag">DIAGNOSTIC / DISTRIBUTION</div><h2 class="display small">How far does one<br><span class="accent">valuable idea travel?</span></h2><div class="question-stack"><p>What happens after you create something?</p><p class="step">How many assets does one idea become?</p><p class="step">Where could you be showing up—but aren’t?</p><p class="step">What existing content is being wasted?</p></div>`,objective:'Measure how effectively created value becomes audience surface area.',ask:'What happens to a valuable idea after its first use?',listen:'No repurposing process, weak channel presence, or forgotten archives.',capture:'Distribution ratio and unused inventory.'},
{act:'V',mode:'ASK',html:`<div class="slide-tag">DIAGNOSTIC / INTELLIGENCE</div><h2 class="display small">Does the machine<br><span class="accent">remember?</span></h2><div class="question-stack"><p>How do you decide what to make next?</p><p class="step">Are you systematically analyzing what works?</p><p class="step">Do questions and comments feed future content?</p><p class="step">What feedback loops actually exist?</p></div>`,objective:'Determine whether the content machine learns systematically.',ask:'Where does learning live after content is published?',listen:'Learning trapped in memory, dashboards without decisions, or no review cadence.',capture:'Feedback inputs and missing loop.'},
{act:'V',mode:'MAP',html:`<div class="slide-tag">FOUNDER FRICTION</div><h2 class="display medium">Where are <span class="accent">you</span><br>the bottleneck?</h2><div class="friction-spectrum"><div class="friction-line"><span>HIGH-VALUE JUDGMENT</span><i></i><span>LOW-VALUE LABOR</span></div><div class="friction-items"><span>IDEATION</span><span>WRITING</span><span>FILMING</span><span>APPROVALS</span><span>RESEARCH</span><span>EDITING</span><span>POSTING</span><span>ANALYZING</span><span>ORGANIZING</span></div></div><p class="footer-claim">Audit the content—and the attention it consumes.</p>`,objective:'Expose where founder attention is being consumed unnecessarily.',ask:'Which work truly requires you, and which work merely waits for you?',listen:'Founder time spent on repeatable operations rather than irreplaceable judgment.',capture:'Founder-led versus system-led work.'},
{act:'VI',mode:'MAP',className:'act-divider',html:`<div class="slide-tag">ACT VI / DEFINE THE GAP</div><div class="act-number">VI</div><h2>Current machine versus required machine.</h2><p>Turn the audit into clarity.</p>`,objective:'Translate the diagnostic into a visible future-state gap.',ask:'What must become structurally different?',listen:'Clear before-and-after shifts rather than vague improvement goals.',capture:'Required state changes.'},
{act:'VI',mode:'MAP',html:`<div class="slide-tag">CURRENT STATE → IDEAL STATE</div><div class="gap-table"><div class="gap-row"><b>IDEAS</b><span>Random / reactive</span><i>→</i><span>Continuous backlog</span></div><div class="gap-row"><b>RESEARCH</b><span>Manual</span><i>→</i><span>AI-assisted</span></div><div class="gap-row"><b>CREATION</b><span>Founder-dependent</span><i>→</i><span>Augmented</span></div><div class="gap-row"><b>DISTRIBUTION</b><span>1 : 1</span><i>→</i><span>1 : many</span></div><div class="gap-row"><b>CONTEXT</b><span>Fragmented</span><i>→</i><span>Structured</span></div><div class="gap-row"><b>ANALYSIS</b><span>Occasional</span><i>→</i><span>Continuous</span></div><div class="gap-row"><b>KNOWLEDGE</b><span>Forgotten</span><i>→</i><span>Compounding</span></div></div>`,objective:'Make the operating gap concrete across seven dimensions.',ask:'Which two or three rows create the greatest leverage if changed?',listen:'High-impact shifts tied to the business goal.',capture:'Top three state gaps.'},
{act:'VI',mode:'TEACH',html:`<div class="slide-tag">ACCURACY OVER COMPLEXITY</div><h2 class="display medium">Do not automate<br><span class="outline">everything.</span></h2><p class="lede step">Find the highest-leverage constraint.<br><strong>Remove it.</strong></p><div class="constraint-pick"><div><b>01</b><span>BIGGEST CONSTRAINT</span></div><div class="step"><b>02</b><span>HIGHEST LEVERAGE</span></div><div class="step"><b>03</b><span>FIRST BUILD</span></div></div>`,objective:'Prevent overbuilding and focus V1 on the highest-leverage constraint.',ask:'If we could remove only one constraint first, which would change the system most?',listen:'A painful, frequent bottleneck connected to the strategic outcome.',capture:'The first-build decision.'},
{act:'VII',mode:'TEACH',className:'act-divider',html:`<div class="slide-tag">ACT VII / HOW AI CLOSES THE GAP</div><div class="act-number">VII</div><h2>What must exist under the hood?</h2><p>Four infrastructure layers power the three engines.</p>`,objective:'Introduce implementation primitives only after the client-facing model is clear.',ask:'Which layer is currently missing beneath your workflows?',listen:'Tools without context, prompts without standards, or work without feedback.',capture:'Infrastructure maturity.'},
{act:'VII',mode:'MAP',html:`<div class="slide-tag">THE INFRASTRUCTURE STACK</div><h2 class="display small">Four layers.<br><span class="accent">One operating system.</span></h2><div class="stack"><div><b>01</b><strong>CONTEXT</strong><span>What the system knows</span></div><div class="step"><b>02</b><strong>SKILLS</strong><span>What the system can do</span></div><div class="step"><b>03</b><strong>WORKFLOWS</strong><span>How work moves</span></div><div class="step"><b>04</b><strong>FEEDBACK</strong><span>How the system improves</span></div></div>`,objective:'Make the proprietary architecture legible in one view.',ask:'Which layer is setting the ceiling today?',listen:'A missing foundation beneath desired automation.',capture:'Layer priority.'},
{act:'VII',mode:'TEACH',html:`<div class="slide-tag">CONTEXT + SKILLS</div><div class="split"><article class="split-card"><small>LAYER 01 / CONTEXT</small><h3>What does it know?</h3><p>Founder. Company. Audience. Offer. Position. Stories. Voice.</p></article><article class="split-card signal step"><small>LAYER 02 / SKILLS</small><h3>What can it do?</h3><p>Interview. Research. Ideate. Hook. Script. Repurpose. Analyze.</p></article></div>`,objective:'Distinguish the intelligence base from reusable AI operating procedures.',ask:'What knowledge and standards must be encoded first?',listen:'High-value tacit knowledge and recurring cognitive jobs.',capture:'Core context domains and skills.'},
{act:'VII',mode:'TEACH',html:`<div class="slide-tag">WORKFLOWS + FEEDBACK</div><h2 class="display small">Move the work.<br><span class="accent">Improve the machine.</span></h2><div class="flow compact"><span>VOICE NOTE</span><i>→</i><span>EXTRACT</span><i>→</i><span>RESEARCH</span><i>→</i><span>SCRIPT</span><i>→</i><span>PUBLISH</span><i>→</i><span>LEARN</span></div><p class="lede step">Performance data + human judgment flow back into <strong>context, skills, ideation, and strategy.</strong></p>`,objective:'Show how individual skills become an operating system and improve over time.',ask:'Where does work stop moving or fail to feed learning back?',listen:'Broken handoffs, no owner, or feedback disconnected from future creation.',capture:'Priority workflow and loop.'},
{act:'VIII',mode:'MAP',className:'act-divider',html:`<div class="slide-tag">ACT VIII / DESIGN THEIR CONTENT OS</div><div class="act-number">VIII</div><h2>What would we actually build for you?</h2><p>Design the minimum viable machine.</p>`,objective:'Turn the training into a focused custom implementation plan.',ask:'What is your highest-leverage build?',listen:'A small set of connected assets that removes the chosen constraint.',capture:'V1 build scope.'},
{act:'VIII',mode:'MAP',html:`<div class="slide-tag">YOUR HIGHEST-LEVERAGE BUILD</div><h2 class="display small">Build only what<br><span class="accent">the gap demands.</span></h2><div class="build-grid"><article class="big-card signal"><b>BUILD 01</b><h3>FOUNDER<br>KNOWLEDGE BASE</h3><p>Expertise. Stories. Opinions. Frameworks. Position.</p></article><article class="big-card step"><b>BUILD 02</b><h3>CREATION<br>ENGINE</h3><p>Interview. Research. Ideation. Hooks. Stories.</p></article><article class="big-card step"><b>BUILD 03</b><h3>DISTRIBUTION<br>LOOP</h3><p>Clips. Written content. Email. Social assets.</p></article></div>`,objective:'Define three connected V1 builds around the diagnosed constraint.',ask:'Which three components create the smallest complete machine?',listen:'A coherent sequence rather than a list of disconnected AI tricks.',capture:'Build components, inputs, and owners.'},
{act:'VIII',mode:'CLOSE',html:`<div class="slide-tag">THE TRANSFORMATION</div><h2 class="display small">From founder friction<br>to <span class="accent">founder leverage.</span></h2><div class="before-after"><article class="state-box"><small>BEFORE</small><blockquote>“What the fuck do I post?”</blockquote></article><div class="state-arrow">→</div><article class="state-box after step"><small>AFTER</small><ul><li>40 relevant ideas</li><li>Research attached</li><li>Suggested angles</li><li>Strong hooks</li><li>Right formats</li><li>Source material</li><li>Prior insights</li><li>Clear next move</li></ul></article></div>`,objective:'End on the lived transformation rather than the technical architecture.',ask:'What would this change about your weekly relationship with content?',listen:'Reduced anxiety, more consistency, higher quality, and reclaimed founder attention.',capture:'Transformation statement and next-session test.'},
{act:'VIII',mode:'CLOSE',html:`<div class="slide-tag">CONTENT OS</div><h2 class="display">AI is not the creator.</h2><p class="lede step"><strong>It is infrastructure around the creator.</strong></p><div class="cycle step"><span>CREATE</span><i>→</i><span>DISTRIBUTE</span><i>→</i><span>LEARN</span><i>→</i><span>CREATE<br>BETTER</span></div><p class="footer-claim">Build the machine. Use it. Learn. Improve.</p>`,objective:'Close the intellectual loop and make the next action obvious.',ask:'What is the first real piece of work we will run through V1?',listen:'A concrete near-term test with meaningful stakes.',capture:'First test case and success criteria.'}
];
const deck=document.querySelector('#deck'),progress=document.querySelector('.progress i'),count=document.querySelector('.slide-count b'),countTotal=document.querySelector('.slide-count span'),actLabel=document.querySelector('.act-label'),modeLabel=document.querySelector('.slide-mode'),presenter=document.querySelector('.presenter'),overview=document.querySelector('.overview');
let index=Math.max(0,Math.min(slides.length-1,(parseInt(location.hash.slice(1),10)||1)-1)),revealed=0;
countTotal.textContent=`/ ${slides.length}`;
slides.forEach((slide,i)=>{const section=document.createElement('section');section.className=`slide mode-${slide.mode.toLowerCase()} ${slide.className||''}`;section.dataset.index=i;section.innerHTML=slide.html;deck.append(section)});
const slideEls=[...document.querySelectorAll('.slide')],actNav=document.querySelector('.act-nav');
acts.forEach(act=>{const button=document.createElement('button');button.innerHTML=`<b>${act.id}</b><span>${act.title}</span><i>${String(act.start+1).padStart(2,'0')}</i>`;button.addEventListener('click',()=>{go(act.start);toggleOverview(false)});actNav.append(button)});
function currentAct(){return acts.find(act=>act.id===slides[index].act)}
function updateNotes(){const slide=slides[index];['objective','ask','listen','capture'].forEach(key=>{document.querySelector(`[data-note="${key}"]`).textContent=slide[key]});document.querySelector('.presenter-title b').textContent=`${String(index+1).padStart(2,'0')} / ${slides.length}`}
function render(){slideEls.forEach((el,i)=>{el.classList.toggle('active',i===index);el.setAttribute('aria-hidden',i!==index);el.querySelectorAll('.step').forEach((step,stepIndex)=>step.classList.toggle('shown',i===index&&stepIndex<revealed))});const act=currentAct();actLabel.textContent=`ACT ${act.id} / ${act.title.toUpperCase()}`;modeLabel.textContent=slides[index].mode;count.textContent=String(index+1).padStart(2,'0');progress.style.width=`${((index+1)/slides.length)*100}%`;updateNotes();history.replaceState(null,'',`#${index+1}`);document.title=`${String(index+1).padStart(2,'0')} — Content OS`}
function go(next){index=Math.max(0,Math.min(slides.length-1,next));revealed=0;render()}
function forward(){const total=slideEls[index].querySelectorAll('.step').length;if(revealed<total){revealed+=1;render()}else if(index<slides.length-1)go(index+1)}
function backward(){if(revealed>0){revealed-=1;render()}else go(index-1)}
function togglePresenter(force){const open=force??!presenter.classList.contains('open');presenter.classList.toggle('open',open);presenter.setAttribute('aria-hidden',!open)}
function toggleOverview(force){const open=force??!overview.classList.contains('open');overview.classList.toggle('open',open);overview.setAttribute('aria-hidden',!open)}
addEventListener('keydown',event=>{if(['ArrowRight',' ','PageDown'].includes(event.key)){event.preventDefault();forward()}if(['ArrowLeft','PageUp'].includes(event.key)){event.preventDefault();backward()}if(event.key.toLowerCase()==='p')togglePresenter();if(event.key.toLowerCase()==='o'||event.key==='Home')toggleOverview(true);if(event.key==='Escape'){togglePresenter(false);toggleOverview(false)}});
document.querySelector('.nav-next').addEventListener('click',forward);document.querySelector('.nav-prev').addEventListener('click',backward);document.querySelectorAll('[data-overview-open]').forEach(button=>button.addEventListener('click',()=>toggleOverview(true)));document.querySelector('[data-overview-close]').addEventListener('click',()=>toggleOverview(false));document.querySelector('[data-presenter-close]').addEventListener('click',()=>togglePresenter(false));let touchX=0;addEventListener('touchstart',event=>{touchX=event.changedTouches[0].clientX},{passive:true});addEventListener('touchend',event=>{const delta=event.changedTouches[0].clientX-touchX;if(Math.abs(delta)>50)delta<0?forward():backward()},{passive:true});
render();
